version: "3.7"
services:
  miniportfolio:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi/miniportfolio:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"
